name: Get Next Tag Version
description: "Get Next Tag Version"
branding:
  icon: 'code'  
  color: 'gray-dark'
runs:
  using: "composite"
  steps:
    - name: Set Tag Name
      shell: bash
      run: |
          git fetch --tags
          newestTag=$(git describe --tags $(git rev-list --tags --max-count=1)) || true
          if [ -z "$newestTag" ]
          then
            newTag="1.0.0"
          else
            newTag="$newestTag"
          fi
          
          numberRegex='([0-9]+(\.[0-9]+)*)' # Corrected regular expression
          if [[ "$newTag" =~ $numberRegex ]]; then
            newTag="${BASH_REMATCH[0]}"
            echo "Extracted version number: $newTag"
          else
            echo "Didn't succeed in extracting the number from $newTag"
            newTag="1.0.0"
          fi

          newTag=$(echo "$newTag" | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
                    
          echo "newestTag=$newestTag"
          echo "newTag=$newTag"
          echo "newTagName=$newTag" >> $GITHUB_ENV
          echo "::set-output name=tagName::$newTag"
